per_listener_settings true
listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/data/password_file
acl_file /mosquitto/data/acl_file
user mosquitto

persistence true
persistence_location /mosquitto/data/
autosave_interval 60

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
